export const types = {
    auth: {
        LOGIN_SUCCCES: 'LOGIN_SUCCCES',
        LOGIN_FAIL: 'LOGIN_FAIL',
        USER_LOADED_SUCCES: 'USER_LOADED_SUCCES',
        USER_LOADED_FAIL: 'USER_LOADED_FAIL',
        AUTHENTICATED_SUCCES: 'AUTHENTICATED_SUCCES',
        AUTHENTICATED_FAIL: 'AUTHENTICATED_FAIL',
        LOGOUT: 'LOGOUT',
        SIGNUP_SUCCCES: 'SIGNUP_SUCCCES',
        SIGNUP_FAIL: 'SIGNUP_FAIL',
        REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS', 
        // PASSWORD_RESET_SUCCES: 'PASSWORD_RESET_SUCCES',
        // PASSWORD_RESET_FAIL: 'PASSWORD_RESET_FAIL',
        // PASSWORD_RESET_CONFIRM_SUCCES: 'PASSWORD_RESET_CONFIRM_SUCCES',
        // PASSWORD_RESET_CONFIRM_FAIL: 'PASSWORD_RESET_CONFIRM_FAIL',
    },
    vacancies: {
        LOAD_AVAILABLE_VACANCIES_SUCCES: 'LOAD_AVAILABLE_VACANCIES_SUCCES',
        LOAD_AVAILABLE_VACANCIES_FAIL: 'LOAD_AVAILABLE_VACANCIES_FAIL',
        LOAD_AVAILABLE_DEPARTMENT_VACANCIES_SUCCES: 'LOAD_AVAILABLE_DEPARTMENT_VACANCIES_SUCCES',
        LOAD_AVAILABLE_DEPARTMENT_VACANCIES_FAIL: 'LOAD_AVAILABLE_DEPARTMENT_VACANCIES_FAIL',
    },
    resumes: {
        LOAD_AVAILABLE_RESUMES_SUCCES: 'LOAD_AVAILABLE_RESUMES_SUCCES',
        LOAD_AVAILABLE_RESUMES_FAIL: 'LOAD_AVAILABLE_RESUMES_FAIL',
        CREATE_NEW_RESUME_SUCCES: 'CREATE_NEW_RESUME_SUCCES',
        CREATE_NEW_RESUME_FAIL: 'CREATE_NEW_RESUME_FAIL',
    }
};