# Generated by Django 4.1.2 on 2022-10-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('description', models.TextField(verbose_name='Description')),
                ('qualification', models.TextField(verbose_name='Qualifications')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='Creator')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyResumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resumes', verbose_name='Resume ID')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacansies', verbose_name='Vacancy ID')),
            ],
        ),
    ]
